name: Build and Deploy Nginx

on:
  push:
    branches:
      - main
    paths:
      - 'docker/nginx-demo/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
   
     - name: Log in to Docker Hub
       uses: docker/login-actions@v3
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: docker/nginx-demo
        push: true
        tags: miketunzy/pi-cluster-nginx:latest

    - name: Deploy to pi-control
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PI_CONTROL_HOST }}
        username: ${{ secrets.PI_CONTROL_USER }}
        key: ${{ secrets.PI_CONTROL_SSH_KEY }}
        script: |
          docker pull miketunzy/pi-cluster-nginx:latest
          docker stop web_server || true
          docker rm web-server || true
          docker run -d -p 8080:80 --name web-server miketunzy/pi-cluster-nginx:latest 
